#uzb bosh qism
bosh_qism='*💟Assalomu alaykum Great Academy o`quv markazi\nrasmiy botiga xush kelibsiz bot orqali barcha kurslarimmiz\nhaqida malumot va kurs uchun\nRo`yxatdan o`tishingiz mumkin*'
matematika_bolim='*💟Matematika kursini tanladingiz marhamat kurs bilan tanishib chiqing📜*'
matematika_info='*💟Matematika kursimiz 0 dan boshlanadi 3 oy o`rganish qism boladi\n3 oy praktika yani Abiturient,DTM barcha variantlar ishlanadi\nKeyin o`qituvchi bilan birgalikda tahlil qilinadi\nMatematika kursimiz 1 oylik narxi 200.000 so`m*'
fizika_bolim='*💟Fizika kursini tanladingiz marhamat kurs bilan tanishib chiqing📜*'
fizika_info='*💟Fizika kursimiz 0 dan boshlanadi 3 oy o`rganish qism boladi\n3 oy praktika yani Abiturient,DTM barcha variantlar ishlanadi\nKeyin o`qituvchi bilan birgalikda tahlil qilinadi\nFizika kursimiz 1 oylik narxi 200.000 so`m*'
info='*Great Academy Toshken shahri Bodomzor metro 22-uyda joylashgan\nBizda malakali o`qutuvchilar ishlashashadi o`zlashtrishda qiynalsangiz\nqo`shimcha dars berida bu bepul kurs davomiyligi 6 oy dan\n\n📍Mo`ljal: Bodomzor metro*'
#rus_qism
bosh_qism_rus='*💟Учебный центр Великой академии Ассаламу алейкум \nДобро пожаловать к официальному боту Для получения дополнительной информации обо всех наших курсах \nnВы можете зарегистрироваться на курс*'
matematika_bolim_rus='*💟Если вы выбрали курс математики, прочтите, пожалуйста, курс курс*'
matem_info_rus='*💟Наш курс математики начинается с 0 3 месяца обучения будет частью 3 месяца практики, т.е. Abiturient, DTM, все варианты будут разработаны Затем проанализированы вместе с учителем Наш курс математики будет стоить 200 000 сумов в месяц*'
fizika_bolim_rus='*💟Если вы выбрали курс физики, прочтите, пожалуйста, курс курс*'
fizika_info_rus='*💟Наш курс физики начинается с 0 3 месяца обучения будет частью 3 месяца практики, т.е. Abiturient, DTM, все варианты будут разработаны Затем проанализированы вместе с учителем Наш курс математики будет стоить 200 000 сумов в месяц*'
info_rus='*Большая Академия расположена на станции метро Бодомзор 22, Ташкент. У нас есть квалифицированные преподаватели.*'